title: "ARIES Science club"
email: scienceclub.aries@gmail.com
timezone: UTC
#baseurl: "/affiliates-jekyll-theme"
permalink: "/:title/"
logo: 'assets/images/aries2.png'
favicon: 'assets/images/aries1.png'
author: Sal
paginate: 5
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  vivek:
    name: Vivek Kumar Jha
    display_name: Vivek Kumar Jha
    avatar: 'assets/images/authors/vivek.jpg'
    email: vivekjha.aries@gmail.com
    web: https://viveikjha.github.io/
    twitter: 
    description: "Vivek Kr. Jha is a Project Associate and a former Ph.D. student at ARIES, Nainital. He is also the mentor of our ARIES Science Club (ASC)."
  krishna:
    name: Dr. Krishna Mohana
    display_name: Dr. Krishna Mohana 
    avatar: 'assets/images/authors/krishna.jpeg'
    email: krishna_mohana@aries.res.in
    web:
    twitter: 
    description: "Dr. krishna Mohana is RA-1 at ARIES, Nainital. He is currently doing research in blazars and AGN."
  shubham:
    name: Shubham Kishore
    display_name: Shubham Kishore 
    avatar: 'assets/images/authors/subham.jpg'
    email: shubham@aries.res.in
    web:
    twitter: 
    description: "Shubham Kishore is a research scholar at ARIES, Nainital. He is currently doing research in blazars."

# Social
social:
  instagram: https://instagram.com/ariesscienceclub?igshid=ZDdkNTZiNTM=
  facebook: https://www.facebook.com/profile.php?id=100090245892539&mibextid=ZbWKwL
  twitter: https://twitter.com/ARIES_SciClub?t=zYVVbsjxHloqHEdTW29sEA&s=09

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
